### ISSUE TITLE
Unable to point dotsecrets to my dotfiles repo.

### ISSUE THREAD

**Issue by flounders** [oohlaf/dotsecrets#2]
The program currently thinks that my dotfiles should only be under ~/dotfiles and is complaining that .dotfilters.yaml is not there. My dotfiles I currently keep under ~/workspace/active_projects/dotfiles and I would like to keep it that way. Are you willing to incorporate a way to give a custom dotfiles path?

**Comment by oohlaf** [comment]
That's already implemented by setting environment variable DOTSECRETS_DOTFILES_PATH to "workspace/active_projects/dotfiles".
